# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesWiki',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candiate_name', models.CharField(max_length=255)),
                ('url_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('title_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('content_wiki', models.TextField(blank=True, null=True)),
                ('images_wiki', models.TextField(blank=True, null=True)),
                ('references_wiki', models.TextField(blank=True, null=True)),
                ('links_wiki', models.TextField(blank=True, null=True)),
                ('sections_wiki', models.TextField(blank=True, null=True)),
                ('summary_wiki', models.TextField(blank=True, null=True)),
                ('fecha_ini_det', models.DateTimeField(blank=True)),
                ('fecha_ini_f', models.DateField(blank=True)),
                ('score', models.IntegerField()),
                ('score_up', models.IntegerField(blank=True, verbose_name='auth.User')),
                ('score_down', models.IntegerField(blank=True, verbose_name='auth.User')),
                ('slug', models.TextField(max_length=15)),
            ],
            options={
                'db_table': 'candidates_wiki',
                'managed': False,
                'get_latest_by': 'fecha_ini_det',
            },
        ),
    ]
