# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidateapp', '0002_candidateuserrelx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate', models.CharField(max_length=225)),
                ('cadidate_desc', models.CharField(max_length=225)),
                ('url_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('title_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('content_wiki', models.TextField(blank=True, null=True)),
                ('images_wiki', models.TextField(blank=True, null=True)),
                ('references_wiki', models.TextField(blank=True, null=True)),
                ('links_wiki', models.TextField(blank=True, null=True)),
                ('sections_wiki', models.TextField(blank=True, null=True)),
                ('summary_wiki', models.TextField(blank=True, null=True)),
                ('reply', models.BooleanField(default=False, verbose_name='Is a reply?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('score_up', models.IntegerField(blank=True, verbose_name='auth.User')),
                ('score_down', models.IntegerField(blank=True, verbose_name='auth.User')),
                ('slug', models.TextField(max_length=15)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
