# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuserrelx',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateuserrelx',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
