# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0004_auto_20180324_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScoreHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateapp.CandidatesWiki')),
            ],
        ),
    ]
