# Generated by Django 2.0.3 on 2018-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0005_candidatescorehist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatescorehist',
            name='candidate_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidatescorehist',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
